import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/features/components/common/Footer";
import { Toaster } from "@/ui/sonner";
import Header from "@/features/components/common/Header/Header";
import { AuthProvider } from "@/features/components/providers/AuthProvider";
import BottomNavigation from "@/features/components/common/BottomNavigation/BottomNavigation";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authNavigation = [
    "/sign-in",
    "/sign-up",
    "/verify-email",
    "/update-password",
    "/password-recovery",
  ];

  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.variable} antialiased min-h-screen flex flex-col`}
      >
        <AuthProvider>
          <Header hideOnRoute={authNavigation} />

          <main className="flex-1 w-full pb-16 md:pb-0">{children}</main>

          <Footer />

          <BottomNavigation
            hideOnRoute={authNavigation}
            className="fixed bottom-0 left-0 right-0 z-50"
          />

          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
